version: '3.7'

services:
  db:
    container_name: profbit-db
    image: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env

  web:
    container_name: profbit-web
    build: ./web
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on: 
      - db

volumes:
  db:
    driver: 'local'
